d<-read.csv("./data/household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
dd <- subset(d, d$Date=="1/2/2007" | d$Date=="2/2/2007")
nd <- dmy_hms(paste(dd$Date,dd$Time))
n<-cbind(dd,nd)
png(file="plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(n$nd, n$Global_active_power, type="l", ylab="Global Active Power", xlab="")
plot(n$nd, n$Voltage, type="l", ylab="Voltage", xlab="datetime")
plot(n$nd,n$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
points(n$nd,n$Sub_metering_2, type="l", col="red")
points(n$nd,n$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black", "red","blue"), lty=1)
plot(n$nd, n$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()